name: Bug Report
description: Create a bug report to help improve PyBrowser
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: pybrowser-version
    attributes:
      label: PyBrowser Version
      description: Which version of PyBrowser are you using?
      placeholder: 1.0.0a
    validations:
      required: true
  - type: input
    attributes:
      label: Device Version
      description: What is your OS version?
      placeholder: e.g. Windows 11 Pro 22H2 22621.755
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots, etc) relevant to this bug.

        Tip: You can attach image(s) or log file(s) by clicking this area to highlight it and then dragging files in.
      placeholder: |
        - Copy the `PyBrowser.log` files from the running directory.
        - Drag and drop them into this text area.